/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  //  这里创建一个doc 的Sidebar https://docusaurus.io/docs/next/sidebar/autogenerated
  // 这里几个Sidebar 就是你在文档的时候 分成几块，比如我们这里需要分成 文档 API 常见问题，这些都会跟着版本走，也能国际化
  // 在导航栏的文档
  docSidebar: [
    // 这里代表 第一个需要引入： docs/index.md 这个页面
    'index',
    // 这里代表 接下来的我们要去扫描指定目录
    {
      // 类型默认 category
      type: 'category',
      // 展示的名称
      label: '快速开始',
      // 默认打开
      collapsed: false,
      // 配置去扫描指定根目录
      items: [
        {
          // 自动扫描 固定
          type: 'autogenerated',
          // 扫描 docs/guides
          dirName: 'guides',
        },
      ],
    },
    {
      // 类型默认 category
      type: 'category',
      // 展示的名称
      label: '设计思考',
      // 默认打开
      collapsed: false,
      // 配置去扫描指定根目录
      items: [
        {
          // 自动扫描 固定
          type: 'autogenerated',
          // 扫描 docs/guides
          dirName: 'design',
        },
      ],
    },
    {
      // 类型默认 category
      type: 'category',
      // 展示的名称
      label: '技术架构',
      // 默认打开
      collapsed: false,
      // 配置去扫描指定根目录
      items: [
        {
          // 自动扫描 固定
          type: 'autogenerated',
          // 扫描 docs/guides
          dirName: 'architecture',
        },
      ],
    },
    {
      // 类型默认 category
      type: 'category',
      // 展示的名称
      label: 'SQL智能助手',
      // 默认打开
      collapsed: false,
      // 配置去扫描指定根目录
      items: [
        {
          // 自动扫描 固定
          type: 'autogenerated',
          // 扫描 docs/guides
          dirName: 'ai',
        },
      ],
    },
    {
      // 类型默认 category
      type: 'category',
      // 展示的名称
      label: '支持的数据库',
      // 默认打开
      collapsed: false,
      // 配置去扫描指定根目录
      items: [
        {
          // 自动扫描 固定
          type: 'autogenerated',
          // 扫描 docs/guides
          dirName: 'dbsupport',
        },
      ],
    },
    {
      // 类型默认 category
      type: 'category',
      // 展示的名称
      label: '数据库管理',
      // 默认打开
      collapsed: false,
      // 配置去扫描指定根目录
      items: [
        {
          // 自动扫描 固定
          type: 'autogenerated',
          // 扫描 docs/guides
          dirName: 'dbmanage',
        },
      ],
    },
    {
      // 类型默认 category
      type: 'category',
      // 展示的名称
      label: '未来规划',
      // 默认打开
      collapsed: false,
      // 配置去扫描指定根目录
      items: [
        {
          // 自动扫描 固定
          type: 'autogenerated',
          // 扫描 docs/guides
          dirName: 'future',
        },
      ],
    },
  ],
  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: '介绍',
  //     item: ['introduction'],
  //   },
  // ],
};

module.exports = sidebars;
